config/routes.rb
Rails.application.routes.draw do
  resources :messages

   root 'messages#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def index
		@messages = Message.all
	end

	def new
		@message = Message.new
	end

	def edit
		@message = Message.find(params[:id])
	end

	def update
		@message = Message.find(params[:id])
		@message.update_attributes(message_params)
		redirect_to messages_path
	end

	def destroy
		@message = Message.find(params[:id])
		@message.destroy
		redirect_to messages_path
	end

	def create
		Message.create(message_params)
		redirect_to messages_path
	end

	private

	def message_params
		params.require(:message).permit(:description)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messageboard</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<div class = "left-nav">
		<ul>
			<li><%= link_to "Home", messages_path %></li>
		</ul>
	</div>
	<div class = "right-nav">
		<ul>
			<li><%= link_to "Add Message", new_message_path %></li>
		</ul>
	</div>
	<div class = "clearfix"></div>
	</header>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>
	<div>
		<%= f.label :description %>
		<%= f.text_field :description %>
	</div>
	<div>
		<%= f.submit %>
	</div>
<% end %>

app/views/messages/edit.html.erb
<h1>Edit Posting</h1>

<%= render "form" %>

app/views/messages/index.html.erb
<h1>Message Board</h1>

<% @messages.each do |message| %>
	<h3><%= message.description %></h3>
	<h5><%= link_to "Edit Posting", edit_message_path(message) %></h5>
	<h5><%= link_to 'Delete Posting', message, method: :delete %></h5>
<% end %>

app/views/messages/new.html.erb
<h1>Add A Message</h1>

<%= render "form" %>